name: Publish image
on:
  push:
    branches:
      - main
      - feature/v1.9.1-arm
jobs:

  build-operator-dep:
      runs-on: ubuntu-18.04
      container: ghcr.io/twiechert/seldon-core/seldon-core-builder:1.0
      steps:
        - uses: actions/checkout@v2
        - name: Generate resources
          run: >-
            cd operator && make generate-resources

        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v2
          with:
            name: generated-operator
            path: operator/generated/**/*

  build-executor-dep:
    runs-on: ubuntu-18.04
    container: ghcr.io/twiechert/seldon-core/seldon-core-builder:1.0
    steps:
      - uses: actions/checkout@v2
      - name: Generate resources
        run: >-
          cd executor && make copy_openapi_resources copy_operator

      - name: Build arm binary
        if: success()
        run: >-
          docker run --rm
          -v /home/runner/work/seldon-core/seldon-core:/go/src/github.com/seldon-core
          -w /home/runner/work/seldon-core/seldon-core/executor
          -e CGO_ENABLED=1
          docker.elastic.co/beats-dev/golang-crossbuild:1.15.10-arm
          --build-cmd "apt-get update -y && apt-get install -y pkg-config && make executor"
          -p "linux/arm64"

      - name: 'Upload executor artifacts'
        uses: actions/upload-artifact@v2
        with:
          name: generated-executor
          path: executor/executor

  build-operator-arm:
    needs: build-operator-dep
    runs-on: ubuntu-latest
    steps:

      - id: repo-lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: generated-operator
          path: /home/runner/work/seldon-core/seldon-core/operator/generated/

      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
      - name: Run Buildx (push image)
        if: success()
        run: >-
          docker buildx build
          --platform linux/arm64/v8
          --tag ghcr.io/${{ steps.repo-lowercase.outputs.lowercase }}/${{ github.event.repository.name }}:1.0.0
          --file ./operator/Dockerfile
          --output "type=image,push=true" ./operator


  build-executor-arm:
    needs: build-executor-dep
    runs-on: ubuntu-latest
    steps:

      - id: repo-lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Download executor api artifacts
        uses: actions/download-artifact@v2
        with:
          name: generated-executor
          path: /home/runner/work/seldon-core/seldon-core/executor/executor


      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
      - name: Run Buildx (push image)
        if: success()
        run: >-
          docker buildx build
          --platform linux/arm64/v8
          --tag ghcr.io/${{ steps.repo-lowercase.outputs.lowercase }}/${{ github.event.repository.name }}-executor:1.0.0
          --file ./executor/Dockerfile.executor
          --output "type=image,push=true" ./executor