name: Publish image
on:
  push:
    branches:
      - main
      - feature/v1.9.1-arm
jobs:

  build-dep:
      runs-on: ubuntu-18.04
      container: ghcr.io/twiechert/seldon-core/seldon-core-builder:1.0
      steps:
        - uses: actions/checkout@v2
        - name: Generate resources
          run: >-
            cd operator && make generate-resources

        - name: 'Upload Artifact'
          uses: actions/upload-artifact@v2
          with:
            name: generated
            path: operator/generated/**/*


  build-arm:
    needs: build-dep
    runs-on: ubuntu-latest
    steps:

      - id: repo-lowercase
        uses: ASzc/change-string-case-action@v1
        with:
          string: ${{ github.repository }}
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: crazy-max/ghaction-docker-buildx@v1
        with:
          version: latest
      - name: Download a single artifact
        uses: actions/download-artifact@v2
        with:
          name: generated
          path: /home/runner/work/seldon-core/seldon-core/operator/generated/

      - name: Login to GitHub Package Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.repository }} --password-stdin
      - name: Run Buildx (push image)
        if: success()
        run: >-
          docker buildx build
          --platform linux/arm64/v8
          --tag ghcr.io/${{ steps.repo-lowercase.outputs.lowercase }}/${{ github.event.repository.name }}:1.0.0
          --file ./operator/Dockerfile
          --output "type=image,push=true" ./operator